import type { NextPage } from 'next'
import Head from 'next/head'

import {CheckCircleIcon} from '@chakra-ui/icons'

import { useEffect, useState } from 'react'
import { Container, List, ListItem ,ListIcon} from '@chakra-ui/react'


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <Container p={5} maxW='container.xl'>
      
        <h3>Bienvenido!</h3>
        <p style={{paddingBottom:"20px"}}>
          Estimado cliente, ahora puedes abrir cuentas de ahorro con nosotros. <br/>
          Presiona el enlace requerido de acuerdo a tus necesidades. Ofrecemos los siguientes servicios:
        </p>

        <List spacing={3}>
          <ListItem>
            <ListIcon as={CheckCircleIcon} color='green.500' />
            <p style={{display:'inline-block'}}>
              Puede darse de alta como cliente.
            </p>
          </ListItem>
          <ListItem>
            <ListIcon as={CheckCircleIcon} color='green.500' />
            <p style={{display:'inline-block'}}>
              Puede aperturar una cuenta de ahorro.
            </p>
          </ListItem>
          <ListItem>
            <ListIcon as={CheckCircleIcon} color='green.500' />
            <p style={{display:'inline-block'}}>
              Puede realizar transacciones como depósitos, retiros y checar movimientos.
            </p>
          </ListItem>
        </List>

      </Container>

    </>
  )
}

export default Home
