import type { NextPage } from 'next'
import Head from 'next/head'

import { useEffect, useState } from 'react'
import { Container} from 'react-bootstrap'


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <Container className='p-5' >
      
        <h3>Bienvenido!</h3>
        <p style={{paddingBottom:"20px"}}>
          Estimado cliente, ahora puedes abrir cuentas de ahorro con nosotros. <br/>
          Presiona el enlace requerido de acuerdo a tus necesidades. Ofrecemos los siguientes servicios:
        </p>


      </Container>

    </>
  )
}

export default Home
