import type { NextPage } from 'next'
import Head from 'next/head'

import { useEffect, useState } from 'react'
import { Container, Form} from 'react-bootstrap'


const Index: NextPage = () => {
  const [cuenta, setCuenta] = useState<boolean>(true);

	useEffect(() => {
		// remueve la barra de navegacion del DOM en la pantalla de iniciar sesión
		let nav : HTMLElement|null= document.querySelector("#topnav");
		if (!!nav) {
			nav.remove();	
		}
	}, []);
	

  return (
    <>
      <Head>
        <title>Inicio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      

      <Container className='p-5' >
      
        <h3>Bienvenido!</h3>
          { cuenta &&
            <p style={{paddingBottom:"20px"}}>
              Inicie sesión si ya tiene una cuenta, o <span className='crear-cuenta' onClick={() => setCuenta(!cuenta)}>cree una nueva</span>.
            </p>
          }
          { !cuenta &&
            <p style={{paddingBottom:"20px"}}>
              LLene sus datos para crear su cuenta, o <span className='crear-cuenta' onClick={() => setCuenta(!cuenta)}>inicie sesión </span>
              si ya tiene una.
            </p>
          }

        { cuenta &&
          <Form className='forma-iniciar-sesion mt-4' >


              <Form.Group className="mb-3 sesion-nombre" controlId="sesion-nombre">
                <Form.Label>Nombre de usuario</Form.Label>
                <Form.Control type="text" style={{width:"280px"}}/>
              </Form.Group>

              <Form.Group className="mb-3 sesion-password" controlId="sesion-password">
                <Form.Label>Contraseña</Form.Label>
                <Form.Control type="password" style={{width:"280px"}} />
              </Form.Group>

          </Form>
        }

        { !cuenta &&
          <Form className='forma-crear-cuenta mt-4' >

              <Form.Group className="mb-3 input-sincuenta forma-nombre" controlId="forma-nombre">
                <Form.Label>Nombre de usuario</Form.Label>
                <Form.Control type="text" style={{width:"280px"}}/>
              </Form.Group>

              <Form.Group className="mb-3 input-sincuenta forma-apellidop" controlId="forma-apellidop">
                <Form.Label>Apellido Paterno</Form.Label>
                <Form.Control type="text" style={{width:"280px"}}/>
              </Form.Group>

              <Form.Group className="mb-3 input-sincuenta forma-apellidom" controlId="forma-apellidom">
                <Form.Label>Apellido Materno</Form.Label>
                <Form.Control type="text" style={{width:"280px"}}/>
              </Form.Group>

              <Form.Group className="mb-3 input-sincuenta forma-correo" controlId="forma-correo">
                <Form.Label>Correo</Form.Label>
                <Form.Control type="email" style={{width:"280px"}}/>
              </Form.Group>

              <Form.Group className="mb-3 input-sincuenta forma-alias" controlId="forma-alias">
                <Form.Label>Alias</Form.Label>
                <Form.Control type="text" style={{width:"280px"}}/>
              </Form.Group>

              <Form.Group className="mb-3 input-sincuenta forma-edad" controlId="forma-edad">
                <Form.Label>Edad</Form.Label>
                <Form.Control type="number" style={{width:"280px"}} step="1" min="0" max="99"/>
              </Form.Group>

              <Form.Group className="mb-3 input-sincuenta forma-edad" controlId="forma-genero">
                <Form.Label>Género</Form.Label>
                <Form.Select aria-label="Default select example" style={{width:"280px"}}>
                  <option>Selecciona una opción</option>
                  <option value="F">Femenino</option>
                  <option value="M">Masculino</option>
                </Form.Select>
              </Form.Group>

              <Form.Group className="mb-3 input-sincuenta forma-password1" controlId="forma-password1">
                <Form.Label>Contraseña</Form.Label>
                <Form.Control type="password" style={{width:"280px"}} />
              </Form.Group>

              <Form.Group className="mb-3 input-sincuenta forma-password2" controlId="forma-password2">
                <Form.Label>Confirmar Contraseña</Form.Label>
                <Form.Control type="password" style={{width:"280px"}} />
              </Form.Group>
          </Form>
        }

      </Container>

    </>
  )
}

export default Index;
