export default interface Usuario {
    usuario_id? : string,
    nombre : string,
    apellido1 : string,
    apellido2? : string,
    alias : string,
    correo : string,
    edad? : number,
    genero : string,
    password : string,
    genero_favorito: string,
    actor_favorito: string,
    dir_favorito: string,
    peli_favorita: string,
}